from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(User)
admin.site.register(Beranda)
admin.site.register(Berita)
admin.site.register(KategoriBerita)
admin.site.register(Kontak)
admin.site.register(KategoriFAQ)
admin.site.register(FAQ)
admin.site.register(jawabanFAQ)
admin.site.register(DetailFAQ)
admin.site.register(Kategori)
admin.site.register(Komentar)
admin.site.register(MisiBPOM)
admin.site.register(TugasBPOM)
admin.site.register(ProfilKaro)
admin.site.register(Tentang)
admin.site.register(Kelompok)
admin.site.register(Subkelompok)
admin.site.register(DetailPelayanan)
admin.site.register(SyaratPelayanan)
admin.site.register(Pelayanan)
admin.site.register(Kategori_pel)
admin.site.register(JenisLaporan)
admin.site.register(Laporan)
admin.site.register(TautanAplikasi)