# Generated by Django 3.1.6 on 2021-03-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beranda',
            name='Photo',
            field=models.ImageField(upload_to='beranda/% Y/% m/% d/', verbose_name='photo beranda'),
        ),
    ]
