# Generated by Django 3.1.6 on 2021-09-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='deskripsi',
            field=models.TextField(default='deskripsi laporan'),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='dokumen',
            field=models.FileField(blank=True, upload_to='laporan'),
        ),
    ]
