# Generated by Django 3.1.6 on 2021-09-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20210908_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='directlink',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='emailsdm',
        ),
        migrations.AddField(
            model_name='kontak',
            name='directlink',
            field=models.URLField(default='link'),
        ),
    ]
