# Generated by Django 3.1.6 on 2021-09-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_tautanaplikasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='tautanaplikasi',
            name='directlink',
            field=models.URLField(default='link'),
        ),
    ]
