# Generated by Django 3.1.6 on 2021-09-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_tautanaplikasi_directlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Galeri',
        ),
    ]
