# Generated by Django 3.1.6 on 2021-03-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_auto_20210308_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='Photo',
            field=models.ImageField(upload_to='berita'),
        ),
    ]
