# Generated by Django 3.1.6 on 2021-03-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_auto_20210308_1250'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kontak',
            new_name='FAQ',
        ),
    ]
