# Generated by Django 3.1.6 on 2021-03-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_galeri_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='create_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
