# Generated by Django 3.1.6 on 2021-03-10 08:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_berita_create_by'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='galeri',
            name='Photo',
            field=models.ImageField(upload_to='galeri', verbose_name='photo galeri'),
        ),
    ]
