# Generated by Django 3.1.6 on 2021-03-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_auto_20210310_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
