# Generated by Django 3.1.6 on 2021-03-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_auto_20210315_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
