# Generated by Django 3.1.6 on 2021-03-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0016_auto_20210317_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentangKami',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_kelompok', models.CharField(max_length=100)),
                ('nm_subkelompok', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
            ],
        ),
    ]
