# Generated by Django 3.1.6 on 2021-03-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0017_tentangkami'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentangkami',
            name='rule',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
