# Generated by Django 3.1.6 on 2021-03-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0019_remove_tentangkami_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subkelompok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_subkelompok', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='tentangkami',
            name='nm_subkelompok',
        ),
        migrations.AddField(
            model_name='tentangkami',
            name='subkelompok_id',
            field=models.ManyToManyField(to='MainApp.Subkelompok'),
        ),
    ]
