# Generated by Django 3.1.6 on 2021-03-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0020_auto_20210319_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('komentar', models.TextField()),
                ('tanggal_berita', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
