# Generated by Django 3.1.6 on 2021-03-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0021_komentar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tentangkami',
            name='subkelompok_id',
        ),
        migrations.AddField(
            model_name='tentangkami',
            name='subkelompok1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tentangkami',
            name='subkelompok2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tentangkami',
            name='subkelompok3',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
