# Generated by Django 3.1.6 on 2021-03-24 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0022_auto_20210323_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tentangkami',
            name='deskripsi',
        ),
    ]
