# Generated by Django 3.1.6 on 2021-03-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0023_remove_tentangkami_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentangkami',
            name='Photo',
            field=models.ImageField(default='tes', upload_to='kami'),
            preserve_default=False,
        ),
    ]
