# Generated by Django 3.1.6 on 2021-03-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0024_tentangkami_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tentangkami',
            name='Photo',
            field=models.ImageField(upload_to='tentangkami'),
        ),
    ]
