# Generated by Django 3.1.6 on 2021-03-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0025_auto_20210324_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='image',
            field=models.ImageField(default='image2', height_field=120, upload_to='berita', width_field=150),
            preserve_default=False,
        ),
    ]
