# Generated by Django 3.1.6 on 2021-03-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0026_berita_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='image',
            field=models.ImageField(height_field=120, upload_to='berita2', width_field=150),
        ),
    ]
