# Generated by Django 3.1.6 on 2021-08-15 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0027_auto_20210326_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berita',
            name='image',
        ),
    ]
