# Generated by Django 3.1.6 on 2021-08-15 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0028_remove_berita_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('NIP', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='beranda',
            old_name='Photo',
            new_name='Photo_beranda',
        ),
        migrations.RenameField(
            model_name='beranda',
            old_name='judul',
            new_name='judul_beranda',
        ),
        migrations.RemoveField(
            model_name='berita',
            name='create_by',
        ),
        migrations.AddField(
            model_name='berita',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.user'),
        ),
    ]
