# Generated by Django 3.1.6 on 2021-08-15 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0029_auto_20210815_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='email',
            new_name='jawaban',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='nama',
            new_name='judul',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='subjek',
            new_name='pertanyaan',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='pesan',
        ),
        migrations.AddField(
            model_name='beranda',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.user'),
        ),
        migrations.AddField(
            model_name='faq',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.user'),
        ),
        migrations.AddField(
            model_name='galeri',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.user'),
        ),
    ]
