# Generated by Django 3.1.6 on 2021-08-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0030_auto_20210815_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='jawaban',
            field=models.CharField(max_length=500),
        ),
    ]
