# Generated by Django 3.1.6 on 2021-08-18 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0031_auto_20210817_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriFAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judulFAQ', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='faq',
            name='judul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.kategorifaq'),
        ),
    ]
