# Generated by Django 3.1.6 on 2021-08-18 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0032_auto_20210818_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='judul',
            new_name='judul_id',
        ),
    ]
