# Generated by Django 3.1.6 on 2021-08-18 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0033_auto_20210818_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='judul_id',
            new_name='judul',
        ),
    ]
