# Generated by Django 3.1.6 on 2021-08-18 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0034_auto_20210818_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='judul',
        ),
    ]
