# Generated by Django 3.1.6 on 2021-08-18 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0037_kategorifaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='judul_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.kategorifaq'),
        ),
    ]
