# Generated by Django 3.1.6 on 2021-08-19 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0039_auto_20210818_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPelayanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syarat_pelayanan', models.TextField()),
                ('infografis', models.ImageField(upload_to='pelayanan')),
                ('dokumen', models.FileField(upload_to='pelayanan')),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KelompokSDM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_kelompok', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pelayanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_pelayanan', models.CharField(max_length=100)),
                ('detailpelayanan_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.detailpelayanan')),
                ('kelompok_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.kelompoksdm')),
            ],
        ),
    ]
