# Generated by Django 3.1.6 on 2021-08-19 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0041_auto_20210819_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentangkami',
            name='kelompok_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.kelompoksdm'),
        ),
    ]
