# Generated by Django 3.1.6 on 2021-08-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0042_tentangkami_kelompok_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori_pel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_kategori', models.CharField(max_length=200)),
                ('ket_kategori', models.TextField()),
            ],
        ),
    ]
