# Generated by Django 3.1.6 on 2021-08-22 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0043_kategori_pel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelayanan',
            name='kategori_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_kategori', to='MainApp.kategori_pel'),
        ),
    ]
